/**:
  ros__parameters:
    use_intra_process_comms: true

/**/aruco_tracker:
  ros__parameters:
    frame_id: "base_link"
    tf.send: false
    tf.child_frame_id: "vision_estimate"

/**/main_camera/camera:
  ros__parameters:
    camera: 0
    width: 640
    height: 480
    format:
      "RGB888"
      #AeEnable: false
      #AeFlickerMode: 0
      #AnalogueGain: 2.0
      #AnalogueGainMode: 1
      #AwbEnable: false
      #AwbMode: 0
      #Brightness: 0.0
      #Contrast: 1.0
    ExposureTime: 1500
    ExposureTimeMode: 1
    FrameDurationLimits: [33333, 33333]
    HdrMode:
      0
      #Sharpness: 0.0

# IMX219
# /**/main_camera/camera:
#   ros__parameters:
#     camera: 0
#     width: 640
#     height: 480
#     frame_id: "main_camera_link"
#     format: "RGB888"
#     AeEnable: false
#     AnalogueGain: 8.0
#     ExposureTime: 1000
#     FrameDurationLimits: [33333, 33333]

/**/main_camera/feat_detector:
  ros__parameters:
    feature_plugins: ["aruco"]
    aruco:
      plugin: "clover2::cam_feature::plugins::aruco"
      cornerRefinementMethod: 2
      minMarkerPerimeterRate: 0.075
      adaptiveThreshConstant: 14.0
      marker_dict: "4X4_1000"

/**/main_camera/optical_flow:
  ros__parameters:
    roi: 256

/**/web_video_server:
  ros__parameters:
    port: 8081

/**/mavros/time:
  ros__parameters:
    time_ref_source: "fcu"
    timesync_mode: MAVLINK
    system_time_rate: 0.0
    timesync_rate: 10.0

/**/mavros/distance_sensor:
  ros__parameters:
    config: |
      distance_sensor/filtred:
        id: 0
        frame_id: "main_camera_link"
        orientation: "PITCH_270"
        field_of_view: 0.0
      distance_sensor/rangefinder:
        subscriber: true
        id: 1
        frame_id: "main_camera_link"
        orientation: "PITCH_270"
        field_of_view: 0.0
