/**/http:
  ros__parameters:
    address: "0.0.0.0"
    port: 3000

    ros_support:
      topics_rate_limit_bps: 100000.0

    map_server:
      map_node: "map_server"

    settings_server:
      schema_path: $(find-pkg-share clover2_sim)/schemas/klever5.yaml
      values_path: "$(env CLOVER2_CONFIG_FILE)"

/**/web_video_server:
  ros__parameters:
    port: 8081
    default_qos_profile: sensor_data
