#!/bin/sh
#
# @name Gazebo Klever5
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

set PARAM_DEFAULTS_VER 3

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=klever5}

param set-default SIM_GZ_EN 1

# PID gains obtained with PX4 autotune for the Klever5 Gazebo model.
param set-default MC_ROLLRATE_P 0.116
param set-default MC_ROLLRATE_I 0.150
param set-default MC_ROLLRATE_D 0.0028

param set-default MC_PITCHRATE_P 0.118
param set-default MC_PITCHRATE_I 0.154
param set-default MC_PITCHRATE_D 0.0028

param set-default MC_YAWRATE_P 0.19
param set-default MC_YAWRATE_I 0.14

param set-default MC_ROLL_P 6.50
param set-default MC_PITCH_P 6.50
param set-default MC_YAW_P 5.07

# Klever5 rotor geometry in Gazebo actuator order, expressed in the
# PX4 FRD body frame (Gazebo uses FLU, so the Y coordinate is inverted).
# 0: front-right (CCW), 1: rear-left (CCW),
# 2: front-left (CW), 3: rear-right (CW).
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.077
param set-default CA_ROTOR0_PY 0.077
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.077
param set-default CA_ROTOR1_PY -0.077
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.077
param set-default CA_ROTOR2_PY -0.077
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.077
param set-default CA_ROTOR3_PY 0.077
param set-default CA_ROTOR3_KM -0.05

# Map PX4 motor functions to Gazebo actuator_number values 0..3.
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0

param set-default SIM_GZ_EC_MAX1 2800
param set-default SIM_GZ_EC_MAX2 2800
param set-default SIM_GZ_EC_MAX3 2800
param set-default SIM_GZ_EC_MAX4 2800


# Klever5 uses external vision for local position and height in simulation.
param set-default SYS_HAS_GPS 0
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_EV_CTRL 11
param set-default EKF2_HGT_REF 2

# Do not trigger position or GCS-link failsafes in the no-GPS simulation.
param set-default COM_POS_FS_EPH 50.0
param set-default NAV_DLL_ACT 0